# Site Info
title: I Pity the foo()!
tagline: "Asaf's technical blog"
description: ""
baseurl: ""
url: http://asafdav2.github.io
logo: "/public/logo.png"

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: "/page/:num"
permalink: "/:year/:title"

version: 1.0.0

# About/contact
author:
  name: Asaf David
  description: Software Developer
  gravatar: fe163847eaf770ac6d7a801a547ecc4a # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/asafdavid
    github:    https://github.com/asafdav2
    facebook:  https://www.facebook.com/ipitythefooblog
    twitter:   https://twitter.com/asafdavid
    # weibo:     http://weibo.com/41173780
    # email:     http://www.google.com/recaptcha/mailhide/d?k=01I3lZFiZYng9N3QxYEtsDaQ==&c=31wAnZkuKqcG0ATAqJN8Z3ln5kkYLA9TwkGc-IbygpM=

# Navigation (2nd level links supported)
nav:
#  Home:           
#    - '/home'
  Blog:           
    - '/'
#    - { Categories: '/categories/' }
    - { Tags: '/tags/' }
#  About:          
#    - '/about/'
  Github: 
    - 'http://www.github.com/asafdav2'

# Where are tags and categories displayed
tag_page: '/tags/'
category_page: '/categories/'

hero:
  image: /public/img/profile.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Puglins
mathjax: true
google_analytics_token: 'UA-54999211-2'
disqus_short_name: 'i-pity-the-foo'


